# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2
build:
   os: ubuntu-lts-latest
   tools:
      python: "3.12"
   jobs:
      post_install:
         - python -m pip --version
         - python -m pip install -e . --group docs

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: doc/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf
